version: '3'

services:
  app:
    build: .
    volumes:
      - .:/usr/src
      - /run/user/1000:/run/user/1000
    ports:
      - "8888:8888"
    environment:
      - XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR}
      - JUPYTER_ENABLE_LAB=yes
      - PYTHONPATH=/usr/src/
